#отображение страницы товара (тест 4)
import time
from selenium import webdriver
from selenium.webdriver.support.select import Select
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

driver = webdriver.Chrome(executable_path='C:/chromedriver.exe')
driver.maximize_window()

driver.get("https://practice.automationtesting.in/")
my_acc_tab = driver.find_element_by_css_selector("ul.main-nav > li:nth-child(2) > a")
my_acc_tab.click()
time.sleep(5)
username_field = driver.find_element_by_id("username")
username_field.send_keys("xeniahrush1505@yandex.ru")
password_field = driver.find_element_by_id("password")
password_field.send_keys("VaKhrushksks15")
time.sleep(5)
login_btn = driver.find_element_by_name("login")
login_btn.click()
time.sleep(5)
shop_tab = driver.find_element_by_css_selector("ul.main-nav > li >a")
shop_tab.click()
time.sleep(5)
html_5_book = driver.find_element_by_css_selector("ul.masonry-done > li:nth-child(3) >a > h3")
html_5_book.click()
book_title = driver.find_element_by_css_selector("div.entry-summary > h1")
book_title_text = book_title.text
assert book_title_text == "HTML5 Forms"
driver.quit()

#количество товаров в категории (тест 5)
driver = webdriver.Chrome(executable_path='C:/chromedriver.exe')
driver.maximize_window()

driver.get("https://practice.automationtesting.in/")
my_acc_tab = driver.find_element_by_css_selector("ul.main-nav > li:nth-child(2) > a")
my_acc_tab.click()
time.sleep(5)
username_field = driver.find_element_by_id("username")
username_field.send_keys("xeniahrush1505@yandex.ru")
password_field = driver.find_element_by_id("password")
password_field.send_keys("VaKhrushksks15")
time.sleep(5)
login_btn = driver.find_element_by_name("login")
login_btn.click()
time.sleep(5)
shop_tab = driver.find_element_by_css_selector("ul.main-nav > li >a")
shop_tab.click()
time.sleep(5)
html_tab = driver.find_element_by_css_selector("ul.product-categories > li:nth-child(2) > a")
html_tab.click()
time.sleep(5)
books = driver.find_elements_by_class_name("woocommerce-LoopProduct-link")
assert len(books) == 3
driver.quit()

#сортировка товаров (тест 6)
driver = webdriver.Chrome(executable_path='C:/chromedriver.exe')
driver.maximize_window()

driver.get("https://practice.automationtesting.in/")
my_acc_tab = driver.find_element_by_css_selector("ul.main-nav > li:nth-child(2) > a")
my_acc_tab.click()
time.sleep(10)
username_field = driver.find_element_by_id("username")
username_field.send_keys("xeniahrush1505@yandex.ru")
password_field = driver.find_element_by_id("password")
password_field.send_keys("VaKhrushksks15")
time.sleep(5)
login_btn = driver.find_element_by_name("login")
login_btn.click()
time.sleep(5)
shop_tab = driver.find_element_by_css_selector("ul.main-nav > li >a")
shop_tab.click()
time.sleep(5)
selector_1 = driver.find_element_by_class_name("orderby").click()
selected_option = driver.find_element_by_css_selector(".orderby > option:nth-child(1)")
option_check = selected_option.get_attribute("value")
assert option_check == "menu_order"
selector_1 = driver.find_element_by_class_name("orderby") #без этой строчки не срабатывает
select_hightolow = Select(selector_1)
select_hightolow.select_by_value("price-desc")
time.sleep(5)
selector_2 = driver.find_element_by_class_name("orderby").click()
selected_option2 = driver.find_element_by_css_selector(".orderby > option:nth-child(6)")
option_check2 = selected_option2.get_attribute("value")
assert option_check2 == "price-desc"
driver.quit()

#отображение, скидка товара (тест 7), модули импортировала в начале файла
driver = webdriver.Chrome(executable_path='C:/chromedriver.exe')
driver.maximize_window()

driver.get("https://practice.automationtesting.in/")
my_acc_tab = driver.find_element_by_css_selector("ul.main-nav > li:nth-child(2) > a")
my_acc_tab.click()
time.sleep(5)
username_field = driver.find_element_by_id("username")
username_field.send_keys("xeniahrush1505@yandex.ru")
password_field = driver.find_element_by_id("password")
password_field.send_keys("VaKhrushksks15")
time.sleep(5)
login_btn = driver.find_element_by_name("login")
login_btn.click()
time.sleep(5)
shop_tab = driver.find_element_by_css_selector("ul.main-nav > li >a")
shop_tab.click()
time.sleep(5)
android_qsg_btn = driver.find_element_by_css_selector("ul.masonry-done > li:nth-child(1) > a >:nth-child(3)")
android_qsg_btn.click()
time.sleep(5)
previous_price = driver.find_element_by_css_selector(".price > del > span")
previous_price_text = previous_price.text
assert previous_price_text == "₹600.00"
current_price = driver.find_element_by_css_selector(".price > ins > span")
current_price_text = current_price.text
assert current_price_text == "₹450.00"
wait = WebDriverWait(driver,20)
book_img = driver.find_element_by_css_selector(".images > a > img")
book_img.click()
book_img_right_size = wait.until(
EC.visibility_of_element_located((By.ID, "fullResImage"))
)
close_btn = wait.until(
EC.element_to_be_clickable((By.CLASS_NAME, "pp_close"))
)
close_btn.click()
driver.quit()

#проверка цены в корзине (тест 8)
driver = webdriver.Chrome(executable_path='C:/chromedriver.exe')
driver.maximize_window()

driver.get("https://practice.automationtesting.in/")
shop_tab = driver.find_element_by_css_selector("ul.main-nav > li:nth-child(1) > a")
shop_tab.click()
time.sleep(5)
add_btn = driver.find_element_by_css_selector("ul.masonry-done > li:nth-child(4) > a:nth-child(2)")
add_btn.click()
time.sleep(5)
# item = driver.find_element_by_class_name("cartcontents")
# item_text = item.text
# assert item_text == "1 Item"
# rubles = driver.find_element_by_class_name("amount")
# rubles_text = rubles.text
# assert rubles_text == "₹180.00"
basket_tab = driver.find_element_by_class_name("cartcontents")
basket_tab.click()
wait = WebDriverWait(driver, 20)
subtotal = wait.until(
    EC.text_to_be_present_in_element((By.CSS_SELECTOR, "td.product-price > span.woocommerce-Price-amount"), "₹180.00")
)
total = wait.until(
    EC.text_to_be_present_in_element((By.CSS_SELECTOR, "strong > .woocommerce-Price-amount"),"₹183.60")
)
driver.quit()

#работа в корзине (тест 9)
driver = webdriver.Chrome(executable_path='C:/chromedriver.exe')
driver.maximize_window()

driver.get("https://practice.automationtesting.in/")
shop_tab = driver.find_element_by_css_selector("ul.main-nav > li:nth-child(1)")
shop_tab.click()
time.sleep(5)
driver.execute_script("window.scrollBy(0, 300);")
add1_btn = driver.find_element_by_css_selector("ul.masonry-done > li:nth-child(4) > a:nth-child(2)")
add1_btn.click()
time.sleep(5)
add2_btn = driver.find_element_by_css_selector("ul.masonry-done > li:nth-child(5) > a:nth-child(2)")
add2_btn.click()
time.sleep(5)
basket = driver.find_element_by_class_name("cartcontents")
basket.click()
time.sleep(5)
delete_btn = driver.find_element_by_css_selector("tr.cart_item > td:nth-child(1) > a")
delete_btn.click()
time.sleep(5)
undo_btn = driver.find_element_by_link_text("Undo?")
undo_btn.click()
quantity1_field = driver.find_element_by_css_selector("tr.cart_item > td:nth-child(5) > div > input")
quantity1_field.clear()
quantity1_field.send_keys("3")
update_btn = driver.find_element_by_name("update_cart")
update_btn.click()
quantity_js = driver.find_element_by_css_selector("div.quantity > input:nth-child(1)")
quantity_js_value = quantity_js.get_attribute("value")
assert quantity_js_value == "3"
time.sleep(5)
apply_btn = driver.find_element_by_name("apply_coupon")
apply_btn.click()
time.sleep(5)
message = driver.find_element_by_css_selector("ul.woocommerce-error > li")
message_text = message.text
assert message_text == "Please enter a coupon code."
driver.quit()

#покупка товара (тест 10)
driver = webdriver.Chrome(executable_path='C:/chromedriver.exe')
driver.maximize_window()

driver.get("https://practice.automationtesting.in/")
shop_tab = driver.find_element_by_css_selector("ul.main-nav > li:nth-child(1)")
shop_tab.click()
time.sleep(5)
driver.execute_script("window.scrollBy(0, 300);")
add_btn = driver.find_element_by_css_selector("ul.masonry-done > li:nth-child(4) > a:nth-child(2)")
add_btn.click()
time.sleep(5)
basket_tab = driver.find_element_by_class_name("cartcontents")
basket_tab.click()
wait = WebDriverWait(driver, 20)
proceed_tochck_btn = wait.until(
    EC.element_to_be_clickable((By.CSS_SELECTOR, "div.wc-proceed-to-checkout > a"))
)
proceed_tochck_btn.click()
first_name_field = wait.until(
    EC.visibility_of_element_located((By.ID, "billing_first_name"))
)
first_name_field.send_keys("Ksenia")
last_name_field = driver.find_element_by_id("billing_last_name")
last_name_field.send_keys("billing_first_name")
email_field = driver.find_element_by_id("billing_email")
email_field.send_keys("xeniahrush1505@yandex.ru")
phone_field = driver.find_element_by_id("billing_phone")
phone_field.send_keys("89910000000")
country_selector = driver.find_element_by_id("s2id_billing_country")
country_selector.click()
country_field = driver.find_element_by_id("s2id_autogen1_search")
country_field.send_keys("Russia")
my_country = driver.find_element_by_css_selector("span.select2-match")
my_country.click()
address_field = driver.find_element_by_id("billing_address_1")
address_field.send_keys("Kuznetsova avenue")
city_field = driver.find_element_by_id("billing_city")
city_field.send_keys("SPb")
state_field = driver.find_element_by_id("billing_state")
state_field.send_keys("SPb")
postcode_field = driver.find_element_by_id("billing_postcode")
postcode_field.send_keys("198328")
time.sleep(10)
driver.execute_script("window.scrollBy(0, 600);")
time.sleep(5)
needed_option = driver.find_element_by_id("payment_method_cheque")
needed_option.click()
place_order_btn = driver.find_element_by_id("place_order")
place_order_btn.click()
thank_message = wait.until(
    EC.text_to_be_present_in_element((By.CLASS_NAME, "woocommerce-thankyou-order-received"),"Thank you. Your order has been received.")
)
payment_method = wait.until(
EC.text_to_be_present_in_element((By.CSS_SELECTOR, "tfoot > tr:nth-child(3) > td"), "Check Payments")
)
driver.quit()
